#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// [에디터 전용] strings.csv → LocData.g.cs 굽기 (§3-4 BalanceExporter와 같은 "수동 전달 차단" 철학).
/// CSV가 유일한 편집 지점 — 번역을 고치면 반드시 이 메뉴를 다시 돌려야 게임에 반영된다.
///
/// 검사까지 겸한다: 중복 키 / 서식 자리표({0}...) 개수가 언어끼리 다른 키 / 빈 번역 통계.
/// 서식 자리표 불일치는 곧 런타임 FormatException이므로 굽기를 중단한다 (조용한 오역보다 시끄러운 실패).
/// </summary>
public static class LocCsvTool
{
    private const string CsvPath = "Assets/Localization/strings.csv";
    private const string OutPath = "Assets/Scripts/Generated/LocData.g.cs";
    private const int LangColumns = 3;   // ko, en, ja (key 다음 3열, 그 뒤는 비고 — 무시)

    [MenuItem("Tools/짜고치는레이스/로컬라이제이션 CSV → 코드 굽기")]
    public static void Bake()
    {
        if (!File.Exists(CsvPath))
        {
            Debug.LogError($"[Loc] CSV 없음: {CsvPath}");
            return;
        }

        var rows = ParseCsv(File.ReadAllText(CsvPath, Encoding.UTF8));
        if (rows.Count == 0) { Debug.LogError("[Loc] CSV가 비었음"); return; }

        var table = new List<(string key, string[] vals)>();
        var seen = new HashSet<string>();
        int emptyEn = 0, emptyJa = 0;
        bool broken = false;

        // rows[0] = 헤더 (key,ko,en,ja,비고) — 건너뜀
        for (int r = 1; r < rows.Count; r++)
        {
            var row = rows[r];
            if (row.Count == 0 || string.IsNullOrWhiteSpace(row[0])) continue;   // 빈 줄
            string key = row[0].Trim();

            if (!seen.Add(key))
            {
                Debug.LogError($"[Loc] 중복 키: {key} (CSV {r + 1}행)");
                broken = true;
                continue;
            }

            var vals = new string[LangColumns];
            for (int c = 0; c < LangColumns; c++)
                vals[c] = c + 1 < row.Count ? row[c + 1] : "";

            if (string.IsNullOrEmpty(vals[0]))
            {
                Debug.LogError($"[Loc] 한국어(원문)가 빈 키: {key} — ko는 폴백이라 비면 안 됨");
                broken = true;
            }
            if (string.IsNullOrEmpty(vals[1])) emptyEn++;
            if (string.IsNullOrEmpty(vals[2])) emptyJa++;

            // 서식 자리표 개수 검증 — 언어끼리 다르면 런타임 FormatException 예약
            int koSlots = CountFormatSlots(vals[0]);
            for (int c = 1; c < LangColumns; c++)
            {
                if (string.IsNullOrEmpty(vals[c])) continue;
                int slots = CountFormatSlots(vals[c]);
                if (slots != koSlots)
                {
                    Debug.LogError($"[Loc] 서식 자리표 불일치: {key} — ko {koSlots}개 vs {(c == 1 ? "en" : "ja")} {slots}개");
                    broken = true;
                }
            }

            table.Add((key, vals));
        }

        if (broken)
        {
            Debug.LogError("[Loc] 오류가 있어 굽기 중단 — CSV를 고치고 다시 실행");
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// LocCsvTool이 Assets/Localization/strings.csv에서 굽는 파일 — 직접 수정 금지.");
        sb.AppendLine("// 갱신: 메뉴 [Tools > 짜고치는레이스 > 로컬라이제이션 CSV → 코드 굽기]");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("internal static class LocData");
        sb.AppendLine("{");
        sb.AppendLine("    // 열 순서: [0]=ko [1]=en [2]=ja  (Loc.Get이 빈 칸을 ko로 폴백)");
        sb.AppendLine("    public static readonly Dictionary<string, string[]> Table = new()");
        sb.AppendLine("    {");
        foreach (var (key, vals) in table)
        {
            sb.Append("        { ").Append(Quote(key)).Append(", new[] { ");
            for (int c = 0; c < vals.Length; c++)
            {
                if (c > 0) sb.Append(", ");
                sb.Append(Quote(vals[c]));
            }
            sb.AppendLine(" } },");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        File.WriteAllText(OutPath, sb.ToString(), new UTF8Encoding(false));
        AssetDatabase.Refresh();
        Debug.Log($"[Loc] 굽기 완료 — 키 {table.Count}개 (en 빈 칸 {emptyEn} / ja 빈 칸 {emptyJa})");
    }

    /// <summary>"{0}" 류 자리표 개수 (최대 인덱스+1). "{{"는 이스케이프라 제외.</summary>
    private static int CountFormatSlots(string s)
    {
        int max = -1;
        for (int i = 0; i < s.Length - 2; i++)
        {
            if (s[i] != '{') continue;
            if (i + 1 < s.Length && s[i + 1] == '{') { i++; continue; }   // {{ 이스케이프
            int j = i + 1, num = 0;
            bool any = false;
            while (j < s.Length && char.IsDigit(s[j])) { num = num * 10 + (s[j] - '0'); j++; any = true; }
            if (any && j < s.Length && (s[j] == '}' || s[j] == ':')) max = Mathf.Max(max, num);
        }
        return max + 1;
    }

    private static string Quote(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "") + "\"";

    /// <summary>따옴표 필드("a,b" / "" 이스케이프 / 필드 안 줄바꿈) 지원하는 CSV 파서. 첫 문자 BOM 제거.</summary>
    private static List<List<string>> ParseCsv(string text)
    {
        if (text.Length > 0 && text[0] == '\uFEFF') text = text.Substring(1);

        var rows = new List<List<string>>();
        var row = new List<string>();
        var field = new StringBuilder();
        bool inQuotes = false;

        for (int i = 0; i < text.Length; i++)
        {
            char ch = text[i];
            if (inQuotes)
            {
                if (ch == '"')
                {
                    if (i + 1 < text.Length && text[i + 1] == '"') { field.Append('"'); i++; }
                    else inQuotes = false;
                }
                else field.Append(ch);
            }
            else switch (ch)
            {
                case '"': inQuotes = true; break;
                case ',': row.Add(field.ToString()); field.Clear(); break;
                case '\r': break;
                case '\n':
                    row.Add(field.ToString()); field.Clear();
                    rows.Add(row); row = new List<string>();
                    break;
                default: field.Append(ch); break;
            }
        }
        if (field.Length > 0 || row.Count > 0)
        {
            row.Add(field.ToString());
            rows.Add(row);
        }
        return rows;
    }
}
#endif
